[tool.poetry]
name = "testing-release-drafter"
version = "0.2.2"
description = ""
authors = ["Kat Samperi <katrina.samperi@iceye.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
