# name: Release Drafter

# on:
#   pull_request:
#     branches:
#       - main

# permissions:
#   contents: read

# jobs:

#   # This will run the labeller and create a new release if one is needed
#   update_release_draft:
#     permissions:
#       # write permission is required to create a github release
#       contents: write
#       # write permission is required for autolabeler
#       # otherwise, read permission is required at least
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       # Drafts your next Release notes as Pull Requests are merged into "main"
#       - uses: release-drafter/release-drafter@v6
#         with:
#           commitish: main
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
